
#define PANDA_MAJOR_VERSION 1
#define PANDA_MINOR_VERSION 8
#define PANDA_SEQUENCE_VERSION 1
#define PANDA_VERSION 1008001
#define PANDA_NUMERIC_VERSION 1008001
#define PANDA_VERSION_STR "1.8.1"
#define PANDA_ABI_VERSION_STR "1.8"
#define PANDA_DISTRIBUTOR "cmu"
#define PANDA_PACKAGE_VERSION_STR "dev"
#define PANDA_PACKAGE_HOST_URL "https://runtime.panda3d.org/"

#define PANDA_OFFICIAL_VERSION
